### PR TITLE
Fix npx upgrade

### PR DESCRIPTION
**Pull request by chrisdickinson**
Ceej and I noticed in the course of upgrading an internal service that reapplying the boltzmann tool to the repo was not setting our `package.json` run scripts as expected. In particular, `boltzmann:upgrade` was being set to `null`. This changeset fixes that: on line 272, in the case where we load an existing package.json, we make sure that the upgrade script is set as expected. Additionally, we switch from `HashMap` to `BTreeMap` in a (vain) attempt to preserve ordering when editing `package.json`. It doesn't _quite_ achieve that – it sorts keys lexically – but it's an improvement over "your keys are now randomly sorted" so I've left it in.

### CODE REVIEW

**Comment by rthai** [comment]
> In particular, `boltzmann:upgrade` was being set to null.

Ha. I thought this was intentional.

**Comment by rthai** [comment]
> It doesn't quite achieve that – it sorts keys lexically – but it's an improvement over "your keys are now randomly sorted" so I've left it in

Ohh this used to be mildly annoying to have to go back in an alpha order my dependencies. I like this change!

**Review by rthai — APPROVED** [review]
Nice!

**Comment by chrisdickinson** [comment]
Thanks for the review!

**Pull request merged**
